#!/bin/bash

raw_secure_file=$1
sorted_file=$2

grep -E -o 'Invalid user .* from (25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' $raw_secure_file | awk '{print $5, $3}' | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n | awk '{print$1}' > $sorted_file 
